### ISSUE TITLE
How to run on a single GPU

### ISSUE THREAD

**Issue by DaDa-zcz** [ZhouYuxuanYX/BlockGCN#18]
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:1 and cpu! (when checking argument for argument tensors in method wrapper_cat)

**Comment by demo4ai** [comment]
Try replacing line 504 with line 503 in the main. py code

**Comment by Minions-Bob** [comment]
> Try replacing line 504 with line 503 in the main. py code
excuse me, Even if I change the code, it still reports an error.            

                                                                                                                                             
  0%|           | 0/626 [00:03<?, ?it/s]
Traceback (most recent call last):
  File "/autodl-fs/data/projects/BlockGCN-main/main.py", line 796, in <module>
    processor.start()
  File "/autodl-fs/data/projects/BlockGCN-main/main.py", line 726, in start
    self.train(epoch, save_model=save_model)
  File "/autodl-fs/data/projects/BlockGCN-main/main.py", line 504, in train
    output, z = self.model(data, F.one_hot(label, num_classes=self.model.num_class), joint)  #一个设备
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/autodl-fs/data/projects/BlockGCN-main/model/BlockGCN.py", line 400, in forward
    a = self.topo(a)
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/autodl-fs/data/projects/BlockGCN-main/model/BlockGCN.py", line 342, in forward
    x = self.pl(x)
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1518, in _wrapped_call_impl
    return self._call_impl(*args, **kwargs)
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/torch/nn/modules/module.py", line 1527, in _call_impl
    return forward_call(*args, **kwargs)
  File "/root/miniconda3/envs/mamba2/lib/python3.10/site-packages/torch_topological/nn/layers.py", line 39, in forward
    centres = torch.cat((centres, 2 * batch[..., -1].unsqueeze(-1)), 2)
RuntimeError: Expected all tensors to be on the same device, but found at least two devices, cuda:0 and cpu! (when checking argument for argument tensors in method wrapper_CUDA_cat)
