### ISSUE TITLE
The number of elements returned by the iteration object in enumerate (process) exceeds the expected limit

### ISSUE THREAD

**Issue by jlustudent22** [ZhouYuxuanYX/BlockGCN#4]
I haven't made any changes to your code, but this issue has occurred. How can I solve it.
Traceback (most recent call last):
  File "/home/xiayt/myproject/BlockGCN/main.py", line 796, in <module>
    processor.start()
  File "/home/xiayt/myproject/BlockGCN/main.py", line 726, in start
    self.train(epoch, save_model=save_model)
  File "/home/xiayt/myproject/BlockGCN/main.py", line 477, in train
    for batch_idx, (data, label, index) in enumerate(process):
ValueError: too many values to unpack (expected 3)

**Comment by ZhouYuxuanYX** [comment]
Hi,

thanks for asking. The main.py is updated and should work fine now.

Best regards

**Comment by ZhouYuxuanYX** [comment]
solved
